#!/usr/bin/env python3
"""Step 4 — Image prompt → image (z-Image-Turbo via ComfyUI).

For every prompt file generated by step3 (*_prompt.txt in the image_gen
dir), injects the prompt plus a fresh random seed into the z-Image-Turbo
ComfyUI workflow, queues it on the local ComfyUI server, waits for the run,
and downloads the generated image into the imgs dir.

The workflow node ids below match image_z_image_turbo.json:
    TEXT_NODE  "57:27"  CLIPTextEncode  → inputs.text  (the prompt)
    SEED_NODE  "57:3"   KSampler        → inputs.seed  (randomized per image)
    SAVE_NODE  "9"      SaveImage       → inputs.filename_prefix (identifiable)

Usage:
    python step4.py [IMAGE_GEN_DIR] [IMGS_DIR] [--workflow PATH]

Defaults:
    IMAGE_GEN_DIR = image_gen/
    IMGS_DIR      = imgs/
    --workflow    = image_z_image_turbo.json (searched: cwd, script dir,
                    ~/project/ComfyUI)
"""

from __future__ import annotations

import argparse
import copy
import json
import random
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

COMFY_URL = "http://127.0.0.1:8188"
TEXT_NODE = "57:27"  # CLIPTextEncode → inputs.text
SEED_NODE = "57:3"   # KSampler → inputs.seed
SAVE_NODE = "9"      # SaveImage → inputs.filename_prefix
QUEUE_TIMEOUT = 60   # seconds to submit the prompt
RUN_TIMEOUT = 600    # seconds to wait for one image to finish
POLL_INTERVAL = 2.0


# ---------------------------------------------------------------------------
# Workflow handling
# ---------------------------------------------------------------------------


def find_workflow(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.exists():
            raise FileNotFoundError(f"--workflow not found: {path}")
        return path
    candidates = [
        Path("image_z_image_turbo.json"),
        Path(__file__).parent / "image_z_image_turbo.json",
        Path.home() / "project/ComfyUI/image_z_image_turbo.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("image_z_image_turbo.json not found; pass --workflow")


def inject_prompt(workflow: dict, text: str, seed: int, filename_prefix: str) -> dict:
    """Return a deep copy of the workflow with the prompt, seed and save
    prefix replaced."""
    wf = copy.deepcopy(workflow)
    wf[TEXT_NODE]["inputs"]["text"] = text
    wf[SEED_NODE]["inputs"]["seed"] = seed
    wf[SAVE_NODE]["inputs"]["filename_prefix"] = filename_prefix
    return wf


# ---------------------------------------------------------------------------
# ComfyUI API
# ---------------------------------------------------------------------------


def _post_json(url: str, payload: dict, timeout: int) -> dict:
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=timeout) as resp:
        if resp.status != 200:
            raise RuntimeError(f"POST {url} returned HTTP {resp.status}")
        return json.loads(resp.read().decode("utf-8"))


def queue_prompt(workflow: dict) -> str:
    """Queue a workflow on ComfyUI; returns the prompt_id."""
    data = _post_json(f"{COMFY_URL}/prompt", {"prompt": workflow}, QUEUE_TIMEOUT)
    prompt_id = data.get("prompt_id")
    if not prompt_id:
        raise RuntimeError(f"ComfyUI did not accept the prompt: {data}")
    return prompt_id


def wait_for_completion(prompt_id: str, timeout: int = RUN_TIMEOUT) -> list[dict]:
    """Poll /history/{prompt_id} until the run finishes; returns the image
    records from the SaveImage node."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{COMFY_URL}/history/{prompt_id}", timeout=10) as resp:
                history = json.loads(resp.read().decode("utf-8"))
        except Exception:
            time.sleep(POLL_INTERVAL)
            continue

        entry = history.get(prompt_id)
        if entry is not None:
            status = entry.get("status", {})
            if status.get("status_str") == "error":
                raise RuntimeError(f"ComfyUI execution error: {status.get('messages', [])}")
            images: list[dict] = []
            for node_output in entry.get("outputs", {}).values():
                images.extend(node_output.get("images", []))
            if images or status.get("completed"):
                return images
        time.sleep(POLL_INTERVAL)
    raise TimeoutError(f"ComfyUI prompt {prompt_id} did not finish within {timeout}s")


def fetch_image(image: dict, dest: Path) -> None:
    """Download a generated image from /view into dest."""
    query = urllib.parse.urlencode({
        "filename": image["filename"],
        "subfolder": image.get("subfolder", ""),
        "type": image.get("type", "output"),
    })
    with urllib.request.urlopen(f"{COMFY_URL}/view?{query}", timeout=60) as resp:
        if resp.status != 200:
            raise RuntimeError(f"fetching image returned HTTP {resp.status}")
        dest.write_bytes(resp.read())


# ---------------------------------------------------------------------------
# Prompt gathering
# ---------------------------------------------------------------------------


def read_prompts(image_dir: Path) -> list[tuple[str, str]]:
    """Return [(output_stem, prompt_text), ...] from the *_prompt.txt files,
    stripping the trailing '_prompt' from the output stem (so
    s1_summary_1_prompt.txt → image s1_summary_1.png)."""
    files = sorted(image_dir.glob("*_prompt.txt"))
    if not files:
        raise FileNotFoundError(f"No *_prompt.txt files found in {image_dir}")
    result: list[tuple[str, str]] = []
    for path in files:
        stem = path.stem
        if stem.endswith("_prompt"):
            stem = stem[: -len("_prompt")]
        result.append((stem, path.read_text(encoding="utf-8").strip()))
    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate images from prompts via ComfyUI (step 4).")
    parser.add_argument("image_dir", nargs="?", default="image_gen", help="directory with *_prompt.txt files")
    parser.add_argument("imgs_dir", nargs="?", default="imgs", help="where to write PNG images")
    parser.add_argument("--workflow", default=None, help="path to the z-Image-Turbo workflow JSON")
    parser.add_argument("--timeout", type=int, default=RUN_TIMEOUT, help="seconds to wait per image")
    args = parser.parse_args()

    image_dir = Path(args.image_dir)
    imgs_dir = Path(args.imgs_dir)
    imgs_dir.mkdir(parents=True, exist_ok=True)

    workflow_base = json.loads(find_workflow(args.workflow).read_text(encoding="utf-8"))
    prompts = read_prompts(image_dir)

    manifest = []
    for stem, prompt in prompts:
        out_path = imgs_dir / f"{stem}.png"
        print(f"[*] Generating {out_path}")
        try:
            workflow = inject_prompt(workflow_base, prompt, random.randint(0, 2**63 - 1), stem)
            prompt_id = queue_prompt(workflow)
            images = wait_for_completion(prompt_id, timeout=args.timeout)
            if not images:
                raise RuntimeError("workflow finished but produced no images")
            fetch_image(images[0], out_path)
            manifest.append({"prompt_file": f"{stem}_prompt.txt", "prompt": prompt, "image": out_path.name, "status": "ok"})
            print(f"    -> {out_path} ({out_path.stat().st_size} bytes)")
        except Exception as exc:  # log and continue; batch job
            manifest.append({"prompt_file": f"{stem}_prompt.txt", "prompt": prompt, "image": out_path.name, "status": f"error: {exc}"})
            print(f"    FAILED {out_path}: {exc}", file=sys.stderr)

    manifest_path = imgs_dir / "images_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    ok = sum(1 for m in manifest if m["status"] == "ok")
    print(f"-> {manifest_path} ({ok}/{len(prompts)} images generated)")
    print("Done.")


if __name__ == "__main__":
    main()
